#!/bin/bash
# Initial setup script for TDX CVM after launch.
# This script is copied to and executed on the CVM by the SGX controller
# during the commissioning phase.
#
# SECURITY: This script disables GCP guest agent SSH key management to
# prevent IAM-based SSH key injection attacks. After this runs, the only
# way to SSH into the CVM is via the ephemeral key generated by the SGX
# controller.

set -euo pipefail

echo "=== TDX CVM Initial Setup ==="
echo "Date: $(date)"
echo "Hostname: $(hostname)"
echo "Kernel: $(uname -r)"

# =====================================================================
# STEP 1: Disable GCP Guest Agent SSH Key Management
# =====================================================================
# ATTACK VECTOR: Inside any GCP VM, the guest agent periodically reads
# SSH keys from http://metadata.google.internal/computeMetadata/v1/ and
# updates ~/.ssh/authorized_keys. If someone with GCP project IAM access
# adds an SSH key via the API or Console, the guest agent will pick it
# up — bypassing our SGX-exclusive SSH access.
#
# MITIGATION: Disable the guest agent's SSH key management entirely.
# Since the controller already has SSH access via the ephemeral key
# injected at VM creation, we don't need the guest agent for this.
# =====================================================================

echo ""
echo "--- Disabling GCP guest agent SSH key management ---"

# 1. Save the current authorized_keys (controller's ephemeral key)
#    before we lock things down
CONTROLLER_KEY_FILE="/home/${USER}/.ssh/authorized_keys"
if [ -f "$CONTROLLER_KEY_FILE" ]; then
    CONTROLLER_KEY=$(cat "$CONTROLLER_KEY_FILE")
    echo "✓ Saved controller SSH key"
fi

# 2. Disable google_authorized_keys in sshd_config
#    This command is what the guest agent uses to inject keys into SSH
if [ -f /etc/ssh/sshd_config ]; then
    # Remove any AuthorizedKeysCommand that points to google_authorized_keys
    sudo sed -i 's/^AuthorizedKeysCommand .*google_authorized_keys.*/#&/' /etc/ssh/sshd_config
    sudo sed -i 's/^AuthorizedKeysCommandUser.*/#&/' /etc/ssh/sshd_config
    echo "✓ Disabled google_authorized_keys in sshd_config"
fi

# Also check sshd_config.d/ for drop-in configs
if [ -d /etc/ssh/sshd_config.d ]; then
    for f in /etc/ssh/sshd_config.d/*.conf; do
        if [ -f "$f" ] && grep -q "google_authorized_keys" "$f"; then
            sudo sed -i 's/^AuthorizedKeysCommand .*google_authorized_keys.*/#&/' "$f"
            sudo sed -i 's/^AuthorizedKeysCommandUser.*/#&/' "$f"
            echo "✓ Disabled google_authorized_keys in $f"
        fi
    done
fi

# 3. Disable the guest agent's accounts daemon (manages SSH keys)
#    The google-guest-agent has a component that syncs SSH keys from metadata
sudo mkdir -p /etc/default
if [ -f /etc/default/instance_configs.cfg ]; then
    # The newer guest agent uses instance_configs.cfg
    if ! grep -q "\[Accounts\]" /etc/default/instance_configs.cfg; then
        echo -e "\n[Accounts]\ndeprovision_remove = false\ngroups = \ngrantadminperms = false" | sudo tee -a /etc/default/instance_configs.cfg > /dev/null
    fi
    sudo sed -i 's/^deprovision_remove.*/deprovision_remove = false/' /etc/default/instance_configs.cfg
    echo "✓ Disabled account provisioning in instance_configs.cfg"
fi

# 4. Create/update the guest agent config to disable SSH key management
sudo mkdir -p /etc/google_guest_agent
cat <<'EOF' | sudo tee /etc/google_guest_agent/instance_configs.cfg > /dev/null
[Accounts]
deprovision_remove = false
groups =
gpasswd_add_cmd =
gpasswd_remove_cmd =
groupadd_cmd =
useradd_cmd =

[AccountManager]
disable = true

[Daemons]
accounts_daemon = false
EOF
echo "✓ Created guest agent config disabling account management"

# 5. Restart the guest agent to pick up the new config
if systemctl is-active --quiet google-guest-agent; then
    sudo systemctl restart google-guest-agent
    echo "✓ Restarted google-guest-agent with new config"
elif systemctl is-active --quiet google-guest-agent.service; then
    sudo systemctl restart google-guest-agent.service
    echo "✓ Restarted google-guest-agent.service with new config"
fi

# 6. Ensure authorized_keys has ONLY the controller's key
#    (Overwrite to remove any keys that were added between boot and now)
if [ -n "${CONTROLLER_KEY:-}" ]; then
    echo "$CONTROLLER_KEY" | sudo tee "$CONTROLLER_KEY_FILE" > /dev/null
    sudo chmod 600 "$CONTROLLER_KEY_FILE"
    sudo chown "${USER}:${USER}" "$CONTROLLER_KEY_FILE"
    echo "✓ authorized_keys locked to controller key only"
fi

# 7. Make authorized_keys immutable (extra protection)
#    Even root/guest-agent cannot modify it without removing the flag first
sudo chattr +i "$CONTROLLER_KEY_FILE" 2>/dev/null || true
echo "✓ Made authorized_keys immutable (chattr +i)"

# 8. Block metadata server SSH key endpoint (defense in depth)
#    Even if the guest agent is re-enabled, it won't be able to fetch new keys
#    We use iptables to block outgoing requests to the metadata endpoint
#    that the guest agent uses for SSH key retrieval
sudo iptables -A OUTPUT -d 169.254.169.254 -p tcp --dport 80 \
    -m string --string "ssh-keys" --algo bm \
    -j DROP 2>/dev/null || true
echo "✓ Applied iptables rule to block metadata SSH key queries"

echo ""
echo "--- GCP guest agent SSH hardening complete ---"

# =====================================================================
# STEP 2: Enable IMA Runtime Measurement Policy
# =====================================================================
# IMA maintains a kernel-level measurement log of every file executed,
# mapped, or opened on the system. This log is used by the controller
# during Phase C' to verify post-boot integrity.
#
# On GCP TDX CVMs, the kernel command line is controlled by the
# hypervisor's direct kernel boot mechanism, so modifying GRUB has no
# effect. Instead, we load the IMA policy at runtime by writing to
# /sys/kernel/security/ima/policy. This file is write-once: all rules
# must be written in a single operation before the policy locks.
#
# TRADEOFF: Files accessed before this point in the boot are not
# measured by IMA. However, the first-boot integrity is covered by
# TDX MRTD (static image measurement) and UEFI measured boot
# (PCRs 0-9). IMA covers everything from this point onward.
# =====================================================================
echo ""
echo "--- Enabling IMA runtime measurement policy ---"

# 1. Ensure securityfs is mounted (required for IMA)
if ! mountpoint -q /sys/kernel/security 2>/dev/null; then
    sudo mount -t securityfs securityfs /sys/kernel/security 2>/dev/null || true
fi

# 2. Check if IMA is available
if [ -d "/sys/kernel/security/ima" ]; then
    echo "✓ IMA is available at /sys/kernel/security/ima/"

    # 3. Load the IMA measurement policy (all rules in a single write)
    #    - BPRM_CHECK: measures all executed binaries
    #    - MMAP_CHECK: measures all mmap'd libraries (e.g., shared .so files)
    #    - MODULE_CHECK: measures all loaded kernel modules
    if [ -f "/sys/kernel/security/ima/policy" ]; then
        printf 'measure func=BPRM_CHECK\nmeasure func=MMAP_CHECK mask=MAY_EXEC\nmeasure func=MODULE_CHECK\n' \
            | sudo tee /sys/kernel/security/ima/policy > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            echo "✓ IMA measurement policy loaded (BPRM_CHECK, MMAP_CHECK, MODULE_CHECK)"
        else
            echo "⚠ Failed to write IMA policy (may already be loaded or permission denied)"
        fi
    else
        echo "⚠ IMA policy file not found — CONFIG_IMA_WRITE_POLICY may not be enabled"
    fi

    # 4. Verify IMA is now measuring
    sleep 1
    IMA_COUNT=$(sudo cat /sys/kernel/security/ima/ascii_runtime_measurements 2>/dev/null | wc -l)
    echo "  IMA log entries after policy load: $IMA_COUNT"

    if [ "$IMA_COUNT" -gt "1" ]; then
        echo "✓ IMA is actively measuring files"
    else
        echo "⚠ IMA log has $IMA_COUNT entries — policy may not have loaded"
    fi
else
    echo "⚠ IMA not found at /sys/kernel/security/ima/"
    echo "  Kernel may not have CONFIG_IMA enabled"
fi

# 5. Check PCR-10 availability (vTPM)
if [ -f "/sys/class/tpm/tpm0/pcr-sha1/10" ]; then
    echo "✓ TPM PCR-10 (SHA-1) is available"
    echo "  PCR-10 (SHA-1): $(cat /sys/class/tpm/tpm0/pcr-sha1/10)"
elif [ -f "/sys/class/tpm/tpm0/pcr-sha256/10" ]; then
    echo "✓ TPM PCR-10 (SHA-256) is available"
else
    echo "⚠ TPM PCR-10 not found — vTPM may not be configured"
fi

echo ""
echo "--- IMA setup complete ---"

# =====================================================================
# STEP 2: System Update
# =====================================================================
echo ""
echo "--- Updating system packages ---"
sudo apt-get update -y
sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

# =====================================================================
# STEP 3: Install Essential Packages
# =====================================================================
echo ""
echo "--- Installing essential packages ---"
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
    tpm2-tools \
    build-essential \
    python3 \
    python3-pip \
    curl \
    jq \
    net-tools

# =====================================================================
# STEP 4: Verify TDX Status
# =====================================================================
echo ""
echo "--- Checking TDX status ---"

# Check if configfs-tsm is available (TDX attestation interface)
if [ -d "/sys/kernel/config/tsm/report" ]; then
    echo "✓ TSM report interface is available (TDX supported)"
else
    echo "⚠ TSM report interface not found"
fi

# Check for TDX guest device
if [ -c "/dev/tdx_guest" ] || [ -c "/dev/tdx-guest" ]; then
    echo "✓ TDX guest device found"
else
    echo "⚠ TDX guest device not found (may use configfs-tsm instead)"
fi

# Check kernel support
if dmesg 2>/dev/null | grep -qi "tdx"; then
    echo "✓ TDX mentioned in dmesg"
    dmesg | grep -i "tdx" | head -5
fi

# =====================================================================
# STEP 5: Additional SSH Hardening
# =====================================================================
echo ""
echo "--- Applying SSH hardening ---"

# Disable password authentication
sudo sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
sudo sed -i 's/^#*ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config

# Disable root login
sudo sed -i 's/^#*PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config

# Restart SSH to apply changes
sudo systemctl restart sshd || true

echo ""
echo "=== TDX CVM Initial Setup Complete ==="
echo "IP Address: $(hostname -I | awk '{print $1}')"
echo ""
echo "Security summary:"
echo "  ✓ GCP guest agent SSH key management disabled"
echo "  ✓ authorized_keys locked to controller key only (immutable)"
echo "  ✓ Password authentication disabled"
echo "  ✓ Root login disabled"
echo "  ✓ Metadata SSH key queries blocked"

# # =====================================================================
# # STEP 6: Ensure IMA (Integrity Measurement Architecture) is Active
# # =====================================================================
# # IMA maintains a kernel-level measurement log of every file executed,
# # mapped, or opened on the system. This log is used by the controller
# # during Phase C' to verify post-boot integrity.
# #
# # On Ubuntu 22.04 TDX images, IMA is typically enabled by default, but
# # the 'tcb' policy (which measures all executables, libraries, and
# # kernel modules) may not be active unless ima_policy=tcb is set as
# # a kernel boot parameter.
# # =====================================================================
# echo ""
# echo "--- Checking IMA status ---"

# # 1. Ensure securityfs is mounted (required for IMA)
# if ! mountpoint -q /sys/kernel/security 2>/dev/null; then
#     sudo mount -t securityfs securityfs /sys/kernel/security 2>/dev/null || true
# fi

# # 2. Check if IMA is available
# if [ -d "/sys/kernel/security/ima" ]; then
#     echo "✓ IMA is available at /sys/kernel/security/ima/"

#     # Check if IMA log has entries
#     IMA_COUNT=$(sudo wc -l < /sys/kernel/security/ima/ascii_runtime_measurements 2>/dev/null || echo "0")
#     echo "  IMA log entries: $IMA_COUNT"

#     if [ "$IMA_COUNT" -gt "0" ]; then
#         echo "✓ IMA is actively measuring files"
#     else
#         echo "⚠ IMA log is empty — ima_policy=tcb may not be set"
#     fi
# else
#     echo "⚠ IMA not found at /sys/kernel/security/ima/"
#     echo "  IMA may need to be enabled via kernel parameter: ima_policy=tcb"
# fi

# # 3. Check PCR-10 availability (vTPM)
# if [ -f "/sys/class/tpm/tpm0/pcr-sha1/10" ]; then
#     echo "✓ TPM PCR-10 (SHA-1) is available"
#     echo "  PCR-10 (SHA-1): $(cat /sys/class/tpm/tpm0/pcr-sha1/10)"
# elif [ -f "/sys/class/tpm/tpm0/pcr-sha256/10" ]; then
#     echo "✓ TPM PCR-10 (SHA-256) is available"
# else
#     echo "⚠ TPM PCR-10 not found — vTPM may not be configured"
# fi

# # 4. Ensure ima_policy=tcb is set for future boots (if not already)
# #    This is a best-effort — the current boot already has its IMA policy
# if [ -f "/etc/default/grub" ]; then
#     if ! grep -q "ima_policy=tcb" /etc/default/grub; then
#         echo "  Adding ima_policy=tcb to GRUB for future boots..."
#         sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="\(.*\)"/GRUB_CMDLINE_LINUX_DEFAULT="\1 ima_policy=tcb ima_appraise=off"/' /etc/default/grub
#         sudo update-grub 2>/dev/null || true
#         echo "✓ GRUB updated with ima_policy=tcb (effective on next boot)"
#     else
#         echo "✓ ima_policy=tcb already set in GRUB"
#     fi
# fi

# echo ""
# echo "--- IMA status check complete ---"

echo ""
echo "=== Full Setup Complete ==="
echo "  ✓ SSH hardened (GCP guest agent disabled, keys immutable)"
echo "  ✓ System packages updated"
echo "  ✓ TDX status verified"
echo "  ✓ IMA status checked"
